### ISSUE TITLE
WeixinApi的分享功能暂时失效

### ISSUE THREAD

**Issue by hoosin** [sofish/wechat.js#15]
## 一、时间：2014-12-31

12.30日，微信官方发了个公告：微信公众平台关于整顿诱导分享及诱导关注行为的公告，话说，这个调整绝对是太粗暴了，直接导致WeixinApi的分享功能不能用，官方限制的，应该是WeixinJSBridge.invoke，初步估计，应该是有个白名单，或者检测公众号是否交了300块钱去认证！

果真是城门失火，殃及池鱼啊！WeixinApi又不是用来干坏事儿的，反到给它们拉了一些用户有木有！

## 二、应对

Hack始终是Hack，官方一限制，咱也没辙！只能找破绽！ 
从Android Weixin Apk 中反编译拿到`wxjs.js`，继续调试了会儿，初见端倪，但是依然不能正常work，周末再抽时间看看吧。

## 三、呼吁

微信官方这么一刀切，估计影响的正常用户也是一大批一大批的，在此呼吁各位Coder：

* 一起找Hack，继续保证WeixinApi能正常工作

* 有在腾讯的朋友，或者有朋友在腾讯的朋友，向官方反馈反馈

* 或者其他办法。。。

## 四、提供wxjs.js

感兴趣的朋友，可以下载 [wxjs.js](http://www.baidufe.com/upload/files/2014-12-31_11-46-03_2.js) ，研究研究。

**Comment by liuyanhui** [comment]
6.0.1和6.0都是可以的，最新的6.0.2是不可以的。坑啊！

**Comment by huanglong** [comment]
@RuochenLyu 多谢啊，已经抄了邮件。好急需要用这个功能啊

**Comment by hkongm** [comment]
企业行为的话，让营销部门去找微信交钱吧。
这里问下，这种渠道应该怎么执行？联系谁？我们公司可以花钱

**Comment by bluebug** [comment]
ios下面的另外一种解决方案：
用window.history.pushState或者replaceState将需要跳转的链接写到history，微信分享时就会使用这个链接
限制：链接地址必须是相对路径，因此只能做同域跳转，但是可以考虑在服务器端加二次跳转
android部分版本支持这两个html5方法，也可以使用

**Comment by RuochenLyu** [comment]
@huanglong 虽然我元旦前就发邮件了，但至今无人回复.......
已经用其他方式规避这个问题了，只能等微信正式开放分享接口。

**Comment by dhlwing** [comment]
@RuochenLyu 啥方式 分享一下呗

**Comment by huanglong** [comment]
@RuochenLyu 

我现在开发的网站是美国的一家网站，没有在中国备案，所以在微信开放平台始终无法通过，这方面 wechat 做的太弱了，我同时也申请了 facebook 的一些应用接口，虽说有些也被拒绝了，但是人家官方给了好几千字，带上图文的回复，告诉你是哪里没做规范，如何解决。

![image](https://cloud.githubusercontent.com/assets/670360/5641411/788dede8-95ed-11e4-915a-e799ea14f179.png)

**Comment by RuochenLyu** [comment]
@dhlwing 业务流程的调整

**Comment by houxiaohou** [comment]
发了邮件，两个小时就回复了，答案是否定的。

> Dear ，
> 旧版并未正式发布的分享接口有严重的安全风险已经不再支持使用，为满足此类需求，
> 我们将于未来一两周内发布正式的分享接口，请留意公众平台相关上线公告

**Comment by RuochenLyu** [comment]
新的接口们发布了，包含分享。

https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&key=1420741421&version=6&lang=zh_CN

微信扫码访问测试页面：
![image](https://cloud.githubusercontent.com/assets/1207465/5674809/0adf0e52-97ec-11e4-9c7b-9766e7c96606.png)

**Comment by aliceyi** [comment]
@RuochenLyu  测试页面不能打开

**Comment by houxiaohou** [comment]
@aliceyi 
微信又搞一次，声明页面也下线了，上的太匆忙，声明里面的文档地址也不对，开发者中心也没有文档里面说的jssdk的接口权限。。

**Comment by RuochenLyu** [comment]
http://www.cnblogs.com/txw1958/p/weixin-js.html

**Comment by aliceyi** [comment]
我刚在微信平台上看到一个接口文档，
http://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html#.E5.9B.BE.E5.83.8F.E6.8E.A5.E5.8F.A3 





5541037

发件人： Daniel Hou
发送时间： 2015-01-09 15:28
收件人： sofish/wechat.js
抄送： Alice
主题： Re: [wechat.js] WeixinApi的分享功能暂时失效 (#15)
@aliceyi 
微信又搞一次，声明页面也下线了，上的太匆忙，声明里面的文档地址也不对，开发者中心也没有文档里面说的jssdk的接口权限。。

**Comment by aliceyi** [comment]
不是公众号现在就不能分享了么？
我看有个一个必填项 
appId: '', // 必填，公众号的唯一标识




5541037

发件人： Ruochen Lyu
发送时间： 2015-01-09 15:32
收件人： sofish/wechat.js
抄送： Alice
主题： Re: [wechat.js] WeixinApi的分享功能暂时失效 (#15)
http://www.cnblogs.com/txw1958/p/weixin-js.html

**Comment by aliceyi** [comment]
@RuochenLyu  

## 现在要用分享功能，还是要走下面的流程么？

可以尝试下这个方案：

目前临时流程是，通过邮件临时申请，在微信新sdk开放后请立刻切换，邮件标题：XXX公司XXX产品申请【获取分享状态及设置分享内容】JS接口权限
邮件发送给：benzhu@tencent.com
抄送给： 
你的Leader

邮件内容：
申请的JS接口名称：获取分享状态及设置分享内容JS接口权限
使用该JS接口的具体用途：（详细描述在哪个产品中使用、具体用途等，提供产品截图）
使用该JS接口的域名或具体网址：（如http://aa.wx.qq.com）
希望获得该JS接口权限的认证公众号名称与微信号：（如微信支付，微信号wxzhifu）
业务方产品联系人：（腾讯员工留RTX，非腾讯员工留姓名+电话+邮箱）
业务方开发联系人：（同上）
申请人联系方式：（公司+部门+职位+姓名+电话+邮箱

**Comment by RuochenLyu** [comment]
@aliceyi 直接用新发布的接口呗

**Comment by cmzz** [comment]
新接口上线了、但是需要权限

**Comment by night-king** [comment]
微信JS-SDK使用权限签名算法的服务端实现(.net版本):
http://www.cnblogs.com/deepleo/p/weixinjssdk.html

**Comment by aliceyi** [comment]
这几天微信jsAPI 接口的分享文案是不是有问题了啊，不显示分享内容了。
